sudo: false
language: node_js
node_js:
  - "node"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"

# NPM < v3.10.10 fails with "Error: Missing required argument #1" in
# npm/lib/fetch-package-metadata.js:31:3.
before_install: >
  if [[ "$(npm --version)" = 3.* ]] && [[ "$(npm --version)" != 3.10.10 ]]; then
    npm install --global npm@3
  fi

notifications:
  email: ["andri@dot.ee"]
